

.PHONY: run
run:
	@echo "Running gcs import script..."
	export GOOGLE_APPLICATION_CREDENTIALS='/home/josu/projects/data-engineering-zoomcamp/3. data-warehouse/keys/credentials.json' && uv run web_to_gcs.py
