version: 2

sources:
  - name: raw_data
    description: "Raw data sources for NYC taxi rides"
    database: terraform-demo-484817 # Project ID
    schema: demo_dataset            # Dataset
    tables:
      - name: yellow_tripdata
      - name: green_tripdata